graph TB
A([Upstream: <br /> Who are the decision makers? <br /> How participative is the process? <br /> Who approves the plan?])-->
B[Plan published: <br /> What is the purpose? <br /> Who is the audience? <br /> What are the aims?]-->
C([Downstream: <br /> How is the plan disseminated? <br /> How is it understood, translated, implemented? <br /> Is the plan monitored or evaluated?])

%% Theming
classDef theme fill:NavajoWhite,stroke:#333,stroke-width:2px,font-family:Helvetica;
class A,B,C theme;